version: "3.1"

networks:
  network:
    name: ${API_NAME}

volumes:
  data-volume:

services:
  app:
    container_name: ${API_NAME}-api
    build:
      context: "."
      dockerfile: "Dockerfile.dev"
    command: ["npm", "run", "start:dev"]
    # restart: always
    env_file: ./.env.development
    environment:
      - DB_HOST=db
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    networks:
      - network

  db:
    image: mariadb
    restart: always
    container_name: ${API_NAME}-db
    volumes:
      - data-volume:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - network

  admin:
    image: phpmyadmin
    container_name: ${API_NAME}-admin
    restart: always
    ports:
      - ${ADMIN_PORT}:80
    networks:
      - network
